name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Built-in Tools
        run: |
          PROJECT_DIR=$(dirname $(find . -name "build.gradle*" -o -name "settings.gradle*" | head -n 1))
          cd "$PROJECT_DIR"
          gradle assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: '**/*.apk'
